# You can make apps auto-start here
# Relevant Hyprland wiki section: https://wiki.hyprland.org/Configuring/Keywords/#executing

# Input method
exec-once = fcitx5
exec-once = qs -c overview
exec-once = qs -c noctalia-shell

exec-once = hyprctl output create headless HEADLESS-1

monitor = HEADLESS-1,1920x1080@60,auto,1
