# Put general config stuff here
# Here's a list of every variable: https://wiki.hyprland.org/Configuring/Variables/

# monitor=,addreserved, 0, 0, 0, 0 # Custom reserved area
# monitor =, modeline 118.25 1600 1688 1856 2112 900 903 908 934 -hsync +vsync, 0x0, 1
# monitor = ,modeline 39.75 704 736 808 912 700 703 713 727 -hsync +vsync,0x0,1

xwayland {
  force_zero_scaling = true
}

# HDMI port: mirror display. To see device name, use `hyprctl monitors`
