# You can put custom rules here
# Window/layer rules: https://wiki.hyprland.org/Configuring/Window-Rules/
# Workspace rules: https://wiki.hyprland.org/Configuring/Workspace-Rules/

# ######## Window rules ########

# Uncomment to apply global transparency to all windows:
windowrulev2 = opacity 0.85 override 0.7 override, class:.*
windowrulev2 = opacity 0.95 override 0.7 override, class:org.kde.dolphin
windowrulev2 = opacity 0.95 override 0.7 override, class:zen

# Disable blur for all xwayland apps
# windowrulev2 = noblur, xwayland:1
