# You can put custom rules here
# Window/layer rules: https://wiki.hyprland.org/Configuring/Window-Rules/
# Workspace rules: https://wiki.hyprland.org/Configuring/Workspace-Rules/

# ######## Window rules ########

# Uncomment to apply global transparency to all windows:
windowrule = match:class .*, opacity .85 .7 1
# windowrule = match:class neovide, opacity .85 .7 1
windowrule = match:class kitty, opacity .9 .7 1
windowrule = match:class org.kde.dolphin, opacity .7 .6 1
windowrule = match:class zen, opacity .85 .7 1

# Disable blur for all xwayland apps
# windowrulev2 = noblur, xwayland:1
