preload = ~/Pictures/Wallpaper/bg.png
# preload = ~/Pictures/Background/wall-01.jpg
preload = ~/Pictures/Background/side-view-anime-style-man-portrait.jpg
preload = ~/Pictures/Background/frieren-1.jpg

# wallpaper = eDP-1,~/Pictures/Wallpaper/bg.png
# wallpaper = eDP-1,~/Pictures/Background/side-view-anime-style-man-portrait.jpg
wallpaper = eDP-1,~/Pictures/Background/frieren-1.jpg

splash = true

#fully disable ipc
# ipc = off

