source-file ~/.config/tmux/tmux.reset.conf
set-option -g default-terminal 'screen-254color'
set-option -g terminal-overrides ',xterm-256color:RGB'

set -g prefix C-Space
set -g base-index 1              # start indexing windows at 1 instead of 0
set -g detach-on-destroy off     # don't exit from tmux when closing a session
set -g escape-time 0             # zero-out escape time delay
set -g history-limit 1000000     # increase history size (from 2,000)
set -g renumber-windows on       # renumber all windows when any window is closed
set -g set-clipboard on          # use system clipboard
set -g status-position bottom       # macOS / darwin style
set -g default-terminal "${TERM}"
setw -g mode-keys vi
set -g pane-active-border-style 'fg=magenta,bg=default'
set -g pane-border-style 'fg=brightblack,bg=default'

bind-key -r B run-shell "~/.config/tmux/scripts/sessionizer.sh ~/omerxx/omerxx.com"

set -g @fzf-url-fzf-options '-p 60%,30% --prompt="   " --border-label=" Open URL "'
set -g @fzf-url-history-limit '2000'

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'fcsonline/tmux-thumbs'
set -g @plugin 'sainnhe/tmux-fzf'
set -g @plugin 'wfxr/tmux-fzf-url'
set -g @plugin 'vaaleyard/tmux-dotbar'
set -g @plugin 'omerxx/tmux-sessionx'

set -g @sessionx-bind 'o'
set -g @sessionx-window-height '85%'
set -g @sessionx-window-width '75%'
set -g @sessionx-zoxide-mode 'on'
set -g @continuum-restore 'off'
set -g @resurrect-strategy-nvim 'session'
set -g base-index 1
setw -g pane-base-index 1
set-option -g renumber-windows on

set -g @tmux-dotbar-fg "none"
set -g @tmux-dotbar-bg "none"
set -g @tmux-dotbar-position "bottom"
set -g @tmux-dotbar-justify "absolute-centre"
set -g @tmux-dotbar-left "true"
set -g @tmux-dotbar-status-left "#S" # see code
set -g @tmux-dotbar-right "false"
set -g @tmux-dotbar-status-right "%H:%M" # see code
set -g @tmux-dotbar-window-status-format " #W "
set -g @tmux-dotbar-window-status-separator " • "
set -g @tmux-dotbar-maximized-icon "󰊓"
set -g @tmux-dotbar-show-maximized-icon-for-all-tabs false
set -g @tmux-dotbar-bold-status true
set -g @tmux-dotbar-bold-current-window false
set -g @tmux-dotbar-ssh-enabled true
set -g @tmux-dotbar-ssh-icon '󰌘'
set -g @tmux-dotbar-ssh-icon-only false

set -g status-style bg=default

set -g default-shell /usr/bin/fish

bind T set-option status

run '~/.tmux/plugins/tpm/tpm'
